System tests - Replace AWS keys with OIDC

diff --git a/.github/workflows/system-tests-enterprise.yml b/.github/workflows/system-tests-enterprise.yml
--- a/.github/workflows/system-tests-enterprise.yml
+++ b/.github/workflows/system-tests-enterprise.yml
@@ -16,6 +16,8 @@ name: System Tests Enterprise
 
 permissions:
   contents: read
+  id-token: write   # This is required for requesting the AWS OIDC JWT
+
 
 env:
   MLRUN_PYTHON_PACKAGE_INSTALLER: uv
@@ -24,6 +26,7 @@ on:
   push:
     branches:
       - '.+-system-tests'
+      - 'feature/aws_access_key_control'
 
   schedule:
 
@@ -63,6 +66,22 @@ jobs:
 
     steps:
     - uses: actions/checkout@v5
+    - name: configure aws credentials
+      uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502
+      with:
+        role-to-assume: MLRun-S3-Read
+        role-session-name: mlrun-system-tests-enterprise-{{ github.run_id }}
+        aws-region: us-east-1
+    # Test AWS S3 access
+    - name: Test aws s3 list
+      run: |
+        echo "Testing S3 bucket listing..."
+        aws s3 ls
+        echo "Testing read from igz-public bucket..."
+        aws s3 ls s3://igz-public/
+        echo "Trying to read a file from igz-public bucket..."
+        aws s3 cp s3://igz-public/node-shell-daemonset.yaml ./ || echo "File not found or no access"
+
     - name: Install dependencies
       run: |
         apt-get update -qqy && apt-get install -y sshpass
